export enum ActionTypes {
  SET_IS_HARD_MODE = 'SET_IS_HARD_MODE',
  SET_GAME_SPEED = 'SET_GAME_SPEED',
  SET_HAS_OBSTACLES = 'SET_HAS_OBSTACLES',
  SET_SNAKE_COLOR = 'SET_SNAKE_COLOR',
  SET_FOOD_COLOR = 'SET_FOOD_COLOR'
}
